# Generated by Django 4.2.7 on 2026-02-20 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source_api', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('api_data', models.JSONField(default=dict)),
                ('pdf_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['source_api', 'external_id'], name='papers_pape_source__6862fc_idx'), models.Index(fields=['-published_date'], name='papers_pape_publish_7695b0_idx')],
                'unique_together': {('source_api', 'external_id')},
            },
        ),
    ]
