# Generated by Django 4.2.7 on 2026-02-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='citation_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
