# Generated by Django 4.2.7 on 2026-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_citation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
