# Generated by Django 4.2.7 on 2026-04-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('max_papers', models.IntegerField(default=20)),
                ('sources', models.JSONField(blank=True, default=list, help_text='Preferred sources (arxiv, semantic_scholar, pubmed). Empty = all sources')),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('papers_count_at_last_check', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_updates', to='reports.literaturereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topic_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('new_papers_count', models.IntegerField(default=0)),
                ('new_papers', models.JSONField(default=list)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.literaturereport')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='subscriptions.topicsubscription')),
            ],
            options={
                'db_table': 'subscription_updates',
                'ordering': ['-check_date'],
            },
        ),
        migrations.AddIndex(
            model_name='topicsubscription',
            index=models.Index(fields=['user', 'is_active'], name='topic_subsc_user_id_ca6e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsubscription',
            index=models.Index(fields=['last_checked_at'], name='topic_subsc_last_ch_848bc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicsubscription',
            unique_together={('user', 'topic')},
        ),
        migrations.AddIndex(
            model_name='subscriptionupdate',
            index=models.Index(fields=['subscription', 'check_date'], name='subscriptio_subscri_28a56d_idx'),
        ),
    ]
