# Generated by Django 4.2.7 on 2026-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0002_alter_paper_citation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('report_content', models.TextField()),
                ('papers_analyzed', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='llama-3.3-70b-versatile', max_length=100)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(related_name='reports', to='papers.paper')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reports_lit_created_e2e727_idx'), models.Index(fields=['status'], name='reports_lit_status_bdf61b_idx')],
            },
        ),
    ]
