# Generated by Django 4.2.7 on 2026-04-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='literaturereport',
            index=models.Index(fields=['-created_at'], name='reports_lit_created_e2e727_idx'),
        ),
        migrations.AddIndex(
            model_name='literaturereport',
            index=models.Index(fields=['status'], name='reports_lit_status_bdf61b_idx'),
        ),
    ]
